plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    id 'kotlin-kapt'
    alias(libs.plugins.hilt.android)
    alias(libs.plugins.kotlin.serialization)
    id 'kotlin-parcelize'
    id 'com.google.gms.google-services'
    alias(libs.plugins.ktlint)
}

android {
    namespace 'com.dev_marinov.chatalyze'
    compileSdk 35

    defaultConfig {
        applicationId "com.dev_marinov.chatalyze"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildTypes {
        debug {// 192.168.0.101
            buildConfigField "String", "API_URL_HTTP", "\"http://192.168.0.101:8080\""
            buildConfigField "String", "API_URL_WS", "\"ws://192.168.0.101:8080\""
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

            buildConfigField "String", "API_URL_HTTP", "\"http://192.168.0.101:8080\""
            buildConfigField "String", "API_URL_WS", "\"ws://192.168.0.101:8080\""
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    buildFeatures {
        buildConfig true
        compose true
    }
    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
            excludes += 'META-INF/INDEX.LIST'
            excludes += 'META-INF/versions/9/OSGI-INF/MANIFEST.MF'
        }
    }
}

dependencies {

    implementation libs.kotlin.reflect

    implementation libs.androidx.core.ktx
    implementation libs.androidx.activity.compose

    // To use constraintlayout in compose
    implementation libs.androidx.constraintlayout.compose
    implementation libs.androidx.privacysandbox.tools.core
    implementation libs.androidx.appcompat
    implementation libs.google.material

    implementation platform(libs.compose.bom)
    implementation libs.compose.ui.graphics
    implementation libs.compose.ui
    implementation libs.compose.ui.tooling.preview
    implementation libs.compose.material
    implementation libs.compose.material3
    implementation libs.compose.foundation
    implementation libs.compose.animation
    implementation libs.compose.material.icons.extended
    implementation libs.compose.runtime.livedata

    testImplementation libs.junit4
    androidTestImplementation libs.androidx.test.ext.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation platform(libs.compose.bom)
    androidTestImplementation libs.compose.ui.test.junit4

    // navigation
    implementation libs.androidx.navigation.compose

    // ui
    implementation libs.accompanist.systemuicontroller
    implementation libs.accompanist.coil
    implementation libs.accompanist.permissions

    debugImplementation libs.compose.ui.tooling
    debugImplementation libs.compose.ui.test.manifest

    implementation libs.coil.compose
    implementation libs.coil.svg

    // Room
    implementation libs.room.runtime
    kapt libs.room.compiler
    implementation libs.room.ktx

    // Coroutines
    implementation libs.coroutines.core
    implementation libs.coroutines.android

    // observable / lifecycle
    implementation libs.lifecycle.livedata.ktx
    implementation libs.lifecycle.viewmodel.ktx
    implementation libs.lifecycle.viewmodel.compose
    implementation libs.lifecycle.runtime.compose
    implementation libs.lifecycle.runtime.ktx
    implementation libs.lifecycle.extensions

    // Dagger - Hilt
    implementation libs.hilt.android
    kapt libs.hilt.android.compiler
    kapt libs.androidx.hilt.compiler
    implementation libs.androidx.hilt.navigation.compose

    // retrofit / okhttp
    implementation libs.retrofit
    implementation libs.retrofit.converter.gson
    implementation libs.okhttp
    implementation libs.okhttp.logging.interceptor

    // dataStore
    implementation libs.datastore.core
    implementation libs.collections.immutable
    implementation libs.datastore.preferences

    // serialization
    implementation libs.serialization.json

    // Ktor client
    implementation libs.ktor.client.auth
    implementation libs.ktor.client.okhttp
    implementation libs.ktor.client.android
    implementation libs.ktor.client.core
    implementation libs.ktor.client.cio
    implementation libs.ktor.client.serialization
    implementation libs.ktor.client.websockets
    implementation libs.ktor.client.logging
    implementation libs.logback.classic
    implementation libs.ktor.client.content.negotiation
    implementation libs.ktor.serialization.kotlinx.json
    implementation libs.ktor.client.json

    // animated-navigation
    implementation libs.exyte.animated.navigation.bar

    // Stream Video Compose SDK
    implementation libs.stream.video.android.compose

    implementation libs.kotlinx.datetime

    //firebase notification
    implementation platform(libs.firebase.bom)
    implementation libs.firebase.messaging

    // lottie
    implementation libs.lottie.compose

    // maps
    implementation libs.osmdroid.android
}